@ICanHazDadJokeApp_BaseUrl = https://icanhazdadjoke.com/

GET {{ICanHazDadJokeApp_BaseUrl}}
Accept: text/plain

###

GET {{ICanHazDadJokeApp_BaseUrl}}/search?limit=30
Accept: application/json

###

GET {{ICanHazDadJokeApp_BaseUrl}}/search?limit=30&term=
Accept: application/json

###